### ISSUE TITLE
[BUG] Setup Marqo with Docker Compose

### ISSUE THREAD

**Issue by kdewald** [marqo-ai/marqo#119]
**Describe the bug**
When testing a basic example with Marqo on a project set up with Docker Compose, the requests module fails with the following error:
`requests.exceptions.InvalidSchema: No connection adapters were found for '"http://admin:admin@opensearch-node1:9200"/marqo-simplewiki-demo-all'`

**To Reproduce**
1. Use the following Docker Compose file to set up the infra.
```
version: "3.7"
services:

  # Official Marqo Build
  marqo-rt:
    image: marqoai/marqo:0.0.4
    container_name: marqo-rt
    environment:
      - OPENSEARCH_URL="http://opensearch-node1:9200"
    ports:
      - 8882:8882
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - opensearch-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  opensearch-node1:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```
2. Try to run the simplewiki example against that instance.

**Expected behavior**
Example should work as advertised.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 with  NVidia GeForce 2070 Super (properly recognized by `nvidia-smi`)

**Additional context**
I'm aware the OpenSearch setup is different (I'm using the default from their website) but it's not significantly different from the one provided by Marqo. The failure I see is within the Marqo container, before any API call makes its way to opensearch.
