### ISSUE TITLE
[ENHANCEMENT] Bring linting back to github workflows

### ISSUE THREAD

**Issue by vicilliar** [marqo-ai/marqo#357]
**Is your feature request related to a problem? Please describe.**
Linting was removed from github workflows due to a bug that says `$HOME not set` when using `tj-actions/changed-files@v29.0.1`. Previously, the solution attempted was manually setting the `HOME` environment variable in this manner:

```
- name: Get Changed Directories
      id: changed-dir
      uses: tj-actions/changed-files@v29.0.1
      with:
         dir_names: true
      run:  |
         export HOME=$pwd
```

**Describe the solution you'd like**
The problem with this is that `export` won't work, since different github actions do not share environment variables. Instead, we need to use `$GITHUB_ENV`, similar to this:
```
- name: Set Home
        run: |
          echo HOME=$pwd >> $GITHUB_ENV
```

Documentation: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
